-- Insert sample users
-- INSERT INTO USERS (USERNAME, PASSWORD, ROLE, ENABLED) VALUES ('kiy', '$2a$10$DUMMY_HASH', 'DOCTOR', TRUE);
-- INSERT INTO USERS (USERNAME, PASSWORD, ROLE, ENABLED) VALUES ('john', '$2a$10$DUMMY_HASH', 'DOCTOR', TRUE);
-- INSERT INTO USERS (USERNAME, PASSWORD, ROLE, ENABLED) VALUES ('jane', '$2a$10$DUMMY_HASH', 'PHARMACIST', TRUE);

MERGE INTO USERS (USERNAME, PASSWORD, ROLE, ENABLED) 
KEY (USERNAME) 
VALUES ('Hasan', '$2a$10$DUMMY_HASH', 'DOCTOR', TRUE);

MERGE INTO USERS (USERNAME, PASSWORD, ROLE, ENABLED) 
KEY (USERNAME) 
VALUES ('Amir', '$2a$10$DUMMY_HASH', 'PHARMACIST', TRUE);
